module.exports = {
    ROLE_CLIENT : "CLIENT",
    ROLE_MODERATOR : "MODERATOR",
    ROLE_ADMINISTRATOR : "ADMINISTRATOR",
    ROLE_NONE : null,
    ROLE_CLIENT_LVL : 1,
    ROLE_MODERATOR_LVL : 2,
    ROLE_ADMINISTRATOR_LVL : 3,

    STATUS_ACCEPTED : 'A',
    STATUS_REJECTED : 'R',
    STATUS_WAITING : 'W',

    GENDER_MAN : 'M',
    GENDER_WOMAN : 'W',

    ALCOHOL_TIME_MIN_HIGHEST_LEVEL : 30,
    ALCOHOL_TIME_MOY_HIGHEST_LEVEL : 0.45,
    ALCOHOL_TIME_MAX_HIGHEST_LEVEL : 60,
    ALCOHOL_MIN_ELIMINATION_SPEED_MAN : 0.10,
    ALCOHOL_MOY_ELIMINATION_SPEED_MAN : 0.125,
    ALCOHOL_MAX_ELIMINATION_SPEED_MAN : 0.15,
    ALCOHOL_MIN_ELIMINATION_SPEED_WOMAN : 0.085,
    ALCOHOL_MOY_ELIMINATION_SPEED_WOMAN : 0.0925,
    ALCOHOL_MAX_ELIMINATION_SPEED_WOMAN : 0.10

};
