module.exports = {
    ACCESS_CLIENT : "CLIENT",
    ACCESS_MODERATOR : "MODERATOR",
    ACCESS_ADMINISTRATOR : "ADMINISTRATEUR",
    ACCESS_CLIENT_LVL : 1,
    ACCESS_MODERATOR_LVL : 2,
    ACCESS_ADMINISTRATOR_LVL : 3
}
