module.exports = {
    ROLE_CLIENT : "CLIENT",
    ROLE_MODERATOR : "MODERATOR",
    ROLE_ADMINISTRATOR : "ADMINISTRATEUR",
    ROLE_CLIENT_LVL : 1,
    ROLE_MODERATOR_LVL : 2,
    ROLE_ADMINISTRATOR_LVL : 3
}
